CREATE TABLE IF NOT EXISTS tb_task (
  id UUID PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  completed BOOLEAN NOT NULL,
  user_id UUID REFERENCES tb_user(id) ON DELETE CASCADE ON UPDATE CASCADE
);
